# Generated by Django 3.1.4 on 2020-12-18 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='idNew',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport_news.news', verbose_name='Новости'),
        ),
    ]
