# Generated by Django 3.1.4 on 2020-12-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_news', '0003_auto_20201218_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='DoneOrNot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='PublishedOrNot',
            field=models.BooleanField(default=False),
        ),
    ]
