# Generated by Django 3.1.4 on 2020-12-19 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport_news', '0005_auto_20201219_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriesnews',
            options={'verbose_name': 'Категория новости', 'verbose_name_plural': 'Категории новостей'},
        ),
        migrations.AlterField(
            model_name='categoryparticipants',
            name='ageParticipant',
            field=models.IntegerField(verbose_name='Возраст участников'),
        ),
        migrations.AlterField(
            model_name='categoryparticipants',
            name='weightParticipant',
            field=models.IntegerField(verbose_name='Вес участников'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport_news.users', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='dateCommentAdd',
            field=models.DateField(auto_now=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='events',
            name='DoneOrNot',
            field=models.BooleanField(default=False, verbose_name='Проведение'),
        ),
        migrations.AlterField(
            model_name='events',
            name='New',
            field=models.ManyToManyField(to='sport_news.News', verbose_name='Новость о мероприятие'),
        ),
        migrations.AlterField(
            model_name='events',
            name='Sport',
            field=models.ManyToManyField(to='sport_news.Sports', verbose_name='Вид спорта'),
        ),
        migrations.AlterField(
            model_name='events',
            name='dateEvent',
            field=models.DateField(verbose_name='Дата проведения'),
        ),
        migrations.AlterField(
            model_name='news',
            name='Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport_news.users', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='news',
            name='PublishedOrNot',
            field=models.BooleanField(default=False, verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='news',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport_news.categoriesnews', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='news',
            name='dateAdd',
            field=models.DateField(auto_now=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='results',
            name='Event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport_news.events', verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='results',
            name='Team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport_news.teams', verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='results',
            name='points',
            field=models.IntegerField(verbose_name='Баллы'),
        ),
        migrations.AlterField(
            model_name='sports',
            name='category_participants',
            field=models.ManyToManyField(to='sport_news.CategoryParticipants', verbose_name='Категории участников'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='Sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport_news.sports', verbose_name='Вид спорта'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='Users',
            field=models.ManyToManyField(to='sport_news.Users', verbose_name='Участник команды'),
        ),
        migrations.AlterField(
            model_name='users',
            name='Role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport_news.roles', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='users',
            name='Sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport_news.sports', verbose_name='Вид спорта'),
        ),
        migrations.AlterField(
            model_name='users',
            name='age',
            field=models.IntegerField(verbose_name='Возраст'),
        ),
    ]
