# Generated by Django 2.2.24 on 2021-06-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_news', '0007_auto_20210108_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='header',
            field=models.CharField(default='null', max_length=200, verbose_name='Заголовок новости'),
        ),
    ]
